"""initial database migration

Revision ID: e305a1b8c730
Revises: 
Create Date: 2019-11-07 19:11:46.113474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e305a1b8c730'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('offer_name', sa.String(length=255), nullable=False),
    sa.Column('offer_start_date', sa.DateTime(), nullable=False),
    sa.Column('offer_end_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('duration_end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('software',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('software_name', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('access_link', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('confirmation_code', sa.String(length=255), nullable=False),
    sa.Column('confirmation_time', sa.DateTime(), nullable=True),
    sa.Column('insert_ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('user_group_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(length=128), nullable=False),
    sa.Column('members_min', sa.Integer(), nullable=False),
    sa.Column('members_max', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=False),
    sa.Column('software_id', sa.Integer(), nullable=False),
    sa.Column('user_group_type_id', sa.Integer(), nullable=False),
    sa.Column('current_price', sa.Boolean(), nullable=False),
    sa.Column('insert_ts', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.ForeignKeyConstraint(['user_group_type_id'], ['user_group_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_group_type_id', sa.Integer(), nullable=False),
    sa.Column('customer_invoice_data', sa.Text(), nullable=False),
    sa.Column('insert_ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_group_type_id'], ['user_group_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('in_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_group_id', sa.Integer(), nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('time_added', sa.DateTime(), nullable=False),
    sa.Column('time_removed', sa.DateTime(), nullable=True),
    sa.Column('group_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['user_group_id'], ['user_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('include',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option_included',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('date_removed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['option.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prerequisite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_group_id', sa.Integer(), nullable=False),
    sa.Column('trial_period_start_date', sa.DateTime(), nullable=True),
    sa.Column('trial_period_end_date', sa.DateTime(), nullable=True),
    sa.Column('subscribe_after_trial', sa.Boolean(), nullable=False),
    sa.Column('current_plan_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('offer_start_date', sa.DateTime(), nullable=True),
    sa.Column('offer_end_date', sa.DateTime(), nullable=True),
    sa.Column('date_subscribed', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=False),
    sa.Column('date_unsubscribed', sa.DateTime(), nullable=True),
    sa.Column('insert_ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.ForeignKeyConstraint(['user_group_id'], ['user_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deactivated_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('in_group_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['in_group_id'], ['in_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('plan_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.Column('insert_ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_invoice_data', sa.Text(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('plan_history_id', sa.Integer(), nullable=False),
    sa.Column('invoice_period_start_date', sa.DateTime(), nullable=False),
    sa.Column('invoice_period_end_date', sa.DateTime(), nullable=False),
    sa.Column('invoice_description', sa.String(length=255), nullable=False),
    sa.Column('invoice_amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('invoice_created_ts', sa.DateTime(), nullable=False),
    sa.Column('invoice_due_ts', sa.DateTime(), nullable=False),
    sa.Column('invoice_paid_ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_history_id'], ['plan_history.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice')
    op.drop_table('plan_history')
    op.drop_table('deactivated_users')
    op.drop_table('subscription')
    op.drop_table('prerequisite')
    op.drop_table('option_included')
    op.drop_table('include')
    op.drop_table('in_group')
    op.drop_table('user_group')
    op.drop_table('plan')
    op.drop_table('user_group_type')
    op.drop_table('user_account')
    op.drop_table('software')
    op.drop_table('option')
    op.drop_table('offer')
    # ### end Alembic commands ###
